services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: fruitveg_app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            DATABASE_URL: "mysql://symfony:symfony@db:3306/fruitveg_db?serverVersion=8.0"
        command: php -S 0.0.0.0:8000 -t public

    db:
        image: mysql:8.0
        container_name: fruitveg_db
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: fruitveg_db
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: fruitveg_phpmyadmin
        restart: always
        ports:
            - "8080:80"
        environment:
            PMA_HOST: fruitveg_db
            PMA_USER: symfony
            PMA_PASSWORD: symfony
        depends_on:
            - db
volumes:
    db_data:
